language: python

python:
  - "2.7"
  

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install nose mock coverage pep8 pylint
  - python setup.py develop

before_script:
  - mkdir -p shippable/codecoverage
  - mkdir -p shippable/testresults
# command to run tests, e.g. python setup.py test
script:
  - pep8 --ignore=E501 jenkinsapi/*.py
  - pylint --rcfile=pylintrc jenkinsapi/*.py --disable R0912
 #   - nosetests jenkinsapi_tests 
  - nosetests jenkinsapi_tests --with-xunit --xunit-file=shippable/testresults/nosetests.xml
   # - which python && coverage run --branch jenkinsapi_tests
    #- which python && coverage xml -o shippable/codecoverage/coverage.xml jenkinsapi_tests
